spring:
  application:
    name: tlias-web-managements
    #配置数据库链接信息
  datasource:
    url: jdbc:mysql://localhost:3307/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  #Mybatis的相关配置
  servlet:          #配置文件上传大小
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名开关 
    map-underscore-to-camel-case: true
    #阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: javawebyan
    region: cn-beijing